/**
 *
 * don't edit this file, it's generated by ./dev/data.ts using the state csv file
 *
 */
/**
 * name of state with data
 */
export type StateName =
  | 'All states'
  | 'Arizona'
  | 'California'
  | 'Colorado'
  | 'Connecticut'
  | 'Deleware'
  | 'Florida'
  | 'Georgia'
  | 'Iowa'
  | 'Illinois'
  | 'Kentucky'
  | 'Michigan'
  | 'Minnesota'
  | 'Missouri'
  | 'Mississippi'
  | 'New Jersey'
  | 'New York'
  | 'Pennsylvania'
  | 'Rhode Island'
  | 'South Carolina'
  | 'South Dakota'
  | 'Texas'
  | 'Vermont';

export const stateList: StateName[] = [
  'All states',
  'Arizona',
  'California',
  'Colorado',
  'Connecticut',
  'Deleware',
  'Florida',
  'Georgia',
  'Iowa',
  'Illinois',
  'Kentucky',
  'Michigan',
  'Minnesota',
  'Missouri',
  'Mississippi',
  'New Jersey',
  'New York',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Texas',
  'Vermont'
];

export const stateData = {
  'All states': {
    State: 'All states',
    'Percent in deserts - All': 0.397,
    'Percent in deserts - Black': 0.306,
    'Percent in deserts - White': 0.402,
    'Percent in deserts - Hispanic': 0.544,
    'Chidren under 5 in deserts- rural': 541690,
    'Children under 5 not in deserts- rural': 436904,
    'Children under 5 in deserts- suburban': 935144,
    'Children under 5 not in deserts- suburban': 1696870,
    'Children under 5  in deserts- urban': 372111,
    'Children under 5 not in deserts- urban': 382846,
    'Text box': ''
  },
  Arizona: {
    State: 'Arizona',
    'Percent in deserts - All': 0.33,
    'Percent in deserts - Black': 0.03,
    'Percent in deserts - White': 0.87,
    'Percent in deserts - Hispanic': 0.51,
    'Chidren under 5 in deserts- rural': 72025,
    'Children under 5 not in deserts- rural': 166450,
    'Children under 5 in deserts- suburban': 916931,
    'Children under 5 not in deserts- suburban': 679831,
    'Children under 5  in deserts- urban': 80514,
    'Children under 5 not in deserts- urban': 197435,
    'Text box': 'Text about Arizona'
  },
  California: {
    State: 'California',
    'Percent in deserts - All': 0.16,
    'Percent in deserts - Black': 0.2,
    'Percent in deserts - White': 0.85,
    'Percent in deserts - Hispanic': 0.02,
    'Chidren under 5 in deserts- rural': 53502,
    'Children under 5 not in deserts- rural': 83342,
    'Children under 5 in deserts- suburban': 87777,
    'Children under 5 not in deserts- suburban': 290382,
    'Children under 5  in deserts- urban': 77222,
    'Children under 5 not in deserts- urban': 148809,
    'Text box': 'Text about California'
  },
  Colorado: {
    State: 'Colorado',
    'Percent in deserts - All': 0.7,
    'Percent in deserts - Black': 0.67,
    'Percent in deserts - White': 0.48,
    'Percent in deserts - Hispanic': 0.34,
    'Chidren under 5 in deserts- rural': 21758,
    'Children under 5 not in deserts- rural': 53021,
    'Children under 5 in deserts- suburban': 486175,
    'Children under 5 not in deserts- suburban': 651702,
    'Children under 5  in deserts- urban': 50051,
    'Children under 5 not in deserts- urban': 115294,
    'Text box': 'Text about Colorado'
  },
  Connecticut: {
    State: 'Connecticut',
    'Percent in deserts - All': 0.91,
    'Percent in deserts - Black': 0.03,
    'Percent in deserts - White': 0.49,
    'Percent in deserts - Hispanic': 0.35,
    'Chidren under 5 in deserts- rural': 56079,
    'Children under 5 not in deserts- rural': 22135,
    'Children under 5 in deserts- suburban': 780904,
    'Children under 5 not in deserts- suburban': 185073,
    'Children under 5  in deserts- urban': 43211,
    'Children under 5 not in deserts- urban': 76329,
    'Text box': 'Text about Connecticut'
  },
  Deleware: {
    State: 'Deleware',
    'Percent in deserts - All': 0.55,
    'Percent in deserts - Black': 0.69,
    'Percent in deserts - White': 0.34,
    'Percent in deserts - Hispanic': 0.52,
    'Chidren under 5 in deserts- rural': 29088,
    'Children under 5 not in deserts- rural': 54426,
    'Children under 5 in deserts- suburban': 137083,
    'Children under 5 not in deserts- suburban': 609855,
    'Children under 5  in deserts- urban': 29433,
    'Children under 5 not in deserts- urban': 68735,
    'Text box': 'Text about Deleware'
  },
  Florida: {
    State: 'Florida',
    'Percent in deserts - All': 0.27,
    'Percent in deserts - Black': 1,
    'Percent in deserts - White': 0.04,
    'Percent in deserts - Hispanic': 0.02,
    'Chidren under 5 in deserts- rural': 56239,
    'Children under 5 not in deserts- rural': 28096,
    'Children under 5 in deserts- suburban': 402378,
    'Children under 5 not in deserts- suburban': 641870,
    'Children under 5  in deserts- urban': 70676,
    'Children under 5 not in deserts- urban': 24616,
    'Text box': 'Text about Florida'
  },
  Georgia: {
    State: 'Georgia',
    'Percent in deserts - All': 0.96,
    'Percent in deserts - Black': 0.9,
    'Percent in deserts - White': 0.68,
    'Percent in deserts - Hispanic': 0.48,
    'Chidren under 5 in deserts- rural': 103743,
    'Children under 5 not in deserts- rural': 106828,
    'Children under 5 in deserts- suburban': 221984,
    'Children under 5 not in deserts- suburban': 209531,
    'Children under 5  in deserts- urban': 23314,
    'Children under 5 not in deserts- urban': 158649,
    'Text box': 'Text about Georgia'
  },
  Iowa: {
    State: 'Iowa',
    'Percent in deserts - All': 0.64,
    'Percent in deserts - Black': 0.26,
    'Percent in deserts - White': 0.77,
    'Percent in deserts - Hispanic': 0.55,
    'Chidren under 5 in deserts- rural': 65711,
    'Children under 5 not in deserts- rural': 67143,
    'Children under 5 in deserts- suburban': 837553,
    'Children under 5 not in deserts- suburban': 585144,
    'Children under 5  in deserts- urban': 35247,
    'Children under 5 not in deserts- urban': 108746,
    'Text box': 'Text about Iowa'
  },
  Illinois: {
    State: 'Illinois',
    'Percent in deserts - All': 0.1,
    'Percent in deserts - Black': 0.95,
    'Percent in deserts - White': 0.19,
    'Percent in deserts - Hispanic': 0.51,
    'Chidren under 5 in deserts- rural': 77024,
    'Children under 5 not in deserts- rural': 34157,
    'Children under 5 in deserts- suburban': 374782,
    'Children under 5 not in deserts- suburban': 588623,
    'Children under 5  in deserts- urban': 59702,
    'Children under 5 not in deserts- urban': 134516,
    'Text box': 'Text about Illinois'
  },
  Kentucky: {
    State: 'Kentucky',
    'Percent in deserts - All': 0.75,
    'Percent in deserts - Black': 0.75,
    'Percent in deserts - White': 0.35,
    'Percent in deserts - Hispanic': 0.14,
    'Chidren under 5 in deserts- rural': 81183,
    'Children under 5 not in deserts- rural': 28208,
    'Children under 5 in deserts- suburban': 144902,
    'Children under 5 not in deserts- suburban': 384898,
    'Children under 5  in deserts- urban': 61831,
    'Children under 5 not in deserts- urban': 138485,
    'Text box': 'Text about Kentucky'
  },
  Michigan: {
    State: 'Michigan',
    'Percent in deserts - All': 0.34,
    'Percent in deserts - Black': 0.56,
    'Percent in deserts - White': 0.08,
    'Percent in deserts - Hispanic': 0.84,
    'Chidren under 5 in deserts- rural': 71226,
    'Children under 5 not in deserts- rural': 67315,
    'Children under 5 in deserts- suburban': 822808,
    'Children under 5 not in deserts- suburban': 608304,
    'Children under 5  in deserts- urban': 41176,
    'Children under 5 not in deserts- urban': 75405,
    'Text box': 'Text about Michigan'
  },
  Minnesota: {
    State: 'Minnesota',
    'Percent in deserts - All': 0.08,
    'Percent in deserts - Black': 0.05,
    'Percent in deserts - White': 0.17,
    'Percent in deserts - Hispanic': 0.13,
    'Chidren under 5 in deserts- rural': 37843,
    'Children under 5 not in deserts- rural': 25479,
    'Children under 5 in deserts- suburban': 820410,
    'Children under 5 not in deserts- suburban': 612991,
    'Children under 5  in deserts- urban': 68185,
    'Children under 5 not in deserts- urban': 107684,
    'Text box': 'Text about Minnesota'
  },
  Missouri: {
    State: 'Missouri',
    'Percent in deserts - All': 0.77,
    'Percent in deserts - Black': 0.08,
    'Percent in deserts - White': 0.67,
    'Percent in deserts - Hispanic': 0.2,
    'Chidren under 5 in deserts- rural': 67620,
    'Children under 5 not in deserts- rural': 39560,
    'Children under 5 in deserts- suburban': 436733,
    'Children under 5 not in deserts- suburban': 512113,
    'Children under 5  in deserts- urban': 48395,
    'Children under 5 not in deserts- urban': 59218,
    'Text box': 'Text about Missouri'
  },
  Mississippi: {
    State: 'Mississippi',
    'Percent in deserts - All': 0.98,
    'Percent in deserts - Black': 0.6,
    'Percent in deserts - White': 0.92,
    'Percent in deserts - Hispanic': 0.48,
    'Chidren under 5 in deserts- rural': 59605,
    'Children under 5 not in deserts- rural': 34369,
    'Children under 5 in deserts- suburban': 177351,
    'Children under 5 not in deserts- suburban': 463243,
    'Children under 5  in deserts- urban': 32107,
    'Children under 5 not in deserts- urban': 146552,
    'Text box': 'Text about Mississippi'
  },
  'New Jersey': {
    State: 'New Jersey',
    'Percent in deserts - All': 0.87,
    'Percent in deserts - Black': 0.6,
    'Percent in deserts - White': 0.16,
    'Percent in deserts - Hispanic': 0.05,
    'Chidren under 5 in deserts- rural': 47752,
    'Children under 5 not in deserts- rural': 79388,
    'Children under 5 in deserts- suburban': 357774,
    'Children under 5 not in deserts- suburban': 293666,
    'Children under 5  in deserts- urban': 30018,
    'Children under 5 not in deserts- urban': 126701,
    'Text box': 'Text about New Jersey'
  },
  'New York': {
    State: 'New York',
    'Percent in deserts - All': 0.15,
    'Percent in deserts - Black': 0.07,
    'Percent in deserts - White': 0.17,
    'Percent in deserts - Hispanic': 0.61,
    'Chidren under 5 in deserts- rural': 72196,
    'Children under 5 not in deserts- rural': 35301,
    'Children under 5 in deserts- suburban': 361900,
    'Children under 5 not in deserts- suburban': 402989,
    'Children under 5  in deserts- urban': 44185,
    'Children under 5 not in deserts- urban': 142336,
    'Text box': 'Text about New York'
  },
  Pennsylvania: {
    State: 'Pennsylvania',
    'Percent in deserts - All': 0.23,
    'Percent in deserts - Black': 0.75,
    'Percent in deserts - White': 0.17,
    'Percent in deserts - Hispanic': 0.28,
    'Chidren under 5 in deserts- rural': 43606,
    'Children under 5 not in deserts- rural': 76629,
    'Children under 5 in deserts- suburban': 230365,
    'Children under 5 not in deserts- suburban': 364484,
    'Children under 5  in deserts- urban': 37381,
    'Children under 5 not in deserts- urban': 71615,
    'Text box': 'Text about Pennsylvania'
  },
  'Rhode Island': {
    State: 'Rhode Island',
    'Percent in deserts - All': 0.24,
    'Percent in deserts - Black': 0.39,
    'Percent in deserts - White': 0.98,
    'Percent in deserts - Hispanic': 0.3,
    'Chidren under 5 in deserts- rural': 63178,
    'Children under 5 not in deserts- rural': 49801,
    'Children under 5 in deserts- suburban': 718507,
    'Children under 5 not in deserts- suburban': 556368,
    'Children under 5  in deserts- urban': 59354,
    'Children under 5 not in deserts- urban': 80711,
    'Text box': 'Text about Rhode Island'
  },
  'South Carolina': {
    State: 'South Carolina',
    'Percent in deserts - All': 0.79,
    'Percent in deserts - Black': 0.62,
    'Percent in deserts - White': 0.49,
    'Percent in deserts - Hispanic': 0.51,
    'Chidren under 5 in deserts- rural': 79265,
    'Children under 5 not in deserts- rural': 33659,
    'Children under 5 in deserts- suburban': 317327,
    'Children under 5 not in deserts- suburban': 296063,
    'Children under 5  in deserts- urban': 51959,
    'Children under 5 not in deserts- urban': 123661,
    'Text box': 'Text about South Carolina'
  },
  'South Dakota': {
    State: 'South Dakota',
    'Percent in deserts - All': 0.14,
    'Percent in deserts - Black': 0.42,
    'Percent in deserts - White': 0.48,
    'Percent in deserts - Hispanic': 0.73,
    'Chidren under 5 in deserts- rural': 66797,
    'Children under 5 not in deserts- rural': 52414,
    'Children under 5 in deserts- suburban': 464927,
    'Children under 5 not in deserts- suburban': 373853,
    'Children under 5  in deserts- urban': 43646,
    'Children under 5 not in deserts- urban': 65226,
    'Text box': 'Text about South Dakota'
  },
  Texas: {
    State: 'Texas',
    'Percent in deserts - All': 0.42,
    'Percent in deserts - Black': 0.59,
    'Percent in deserts - White': 0.14,
    'Percent in deserts - Hispanic': 0.83,
    'Chidren under 5 in deserts- rural': 40417,
    'Children under 5 not in deserts- rural': 45788,
    'Children under 5 in deserts- suburban': 458977,
    'Children under 5 not in deserts- suburban': 354912,
    'Children under 5  in deserts- urban': 52077,
    'Children under 5 not in deserts- urban': 131410,
    'Text box': 'Text about Texas'
  },
  Vermont: {
    State: 'Vermont',
    'Percent in deserts - All': 0.9,
    'Percent in deserts - Black': 0.49,
    'Percent in deserts - White': 0.82,
    'Percent in deserts - Hispanic': 0.14,
    'Chidren under 5 in deserts- rural': 54105,
    'Children under 5 not in deserts- rural': 49610,
    'Children under 5 in deserts- suburban': 229892,
    'Children under 5 not in deserts- suburban': 326465,
    'Children under 5  in deserts- urban': 53088,
    'Children under 5 not in deserts- urban': 107070,
    'Text box': 'Text about Vermont'
  }
};
