/**
 *
 * don't edit this file, it's generated by ./dev/data.ts using the state csv file
 *
 */
/**
 * name of state with data
 */
export type StateName =
  | 'All states'
  | 'Arizona'
  | 'California'
  | 'Colorado'
  | 'Connecticut'
  | 'Deleware'
  | 'Florida'
  | 'Georgia'
  | 'Iowa'
  | 'Illinois'
  | 'Kentucky'
  | 'Michigan'
  | 'Minnesota'
  | 'Missouri'
  | 'Mississippi'
  | 'New Jersey'
  | 'New York'
  | 'Pennsylvania'
  | 'Rhode Island'
  | 'South Carolina'
  | 'South Dakota'
  | 'Texas'
  | 'Vermont';

export const stateList: StateName[] = [
  'All states',
  'Arizona',
  'California',
  'Colorado',
  'Connecticut',
  'Deleware',
  'Florida',
  'Georgia',
  'Iowa',
  'Illinois',
  'Kentucky',
  'Michigan',
  'Minnesota',
  'Missouri',
  'Mississippi',
  'New Jersey',
  'New York',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Texas',
  'Vermont'
];

export const stateData = {
  'All states': {
    state: 'All states',
    percentInDesertsAll: 0.397,
    percentInDesertsBlack: 0.306,
    percentInDesertsWhite: 0.402,
    percentInDesertsHispanic: 0.544,
    chidrenUnder5InDesertsRural: 541690,
    childrenUnder5NotInDesertsRural: 436904,
    childrenUnder5InDesertsSuburban: 935144,
    childrenUnder5NotInDesertsSuburban: 1696870,
    childrenUnder5InDesertsUrban: 372111,
    childrenUnder5NotInDesertsUrban: 382846,
    textBox: ''
  },
  Arizona: {
    state: 'Arizona',
    percentInDesertsAll: 0.33,
    percentInDesertsBlack: 0.03,
    percentInDesertsWhite: 0.87,
    percentInDesertsHispanic: 0.51,
    chidrenUnder5InDesertsRural: 72025,
    childrenUnder5NotInDesertsRural: 166450,
    childrenUnder5InDesertsSuburban: 916931,
    childrenUnder5NotInDesertsSuburban: 679831,
    childrenUnder5InDesertsUrban: 80514,
    childrenUnder5NotInDesertsUrban: 197435,
    textBox: 'Text about Arizona'
  },
  California: {
    state: 'California',
    percentInDesertsAll: 0.16,
    percentInDesertsBlack: 0.2,
    percentInDesertsWhite: 0.85,
    percentInDesertsHispanic: 0.02,
    chidrenUnder5InDesertsRural: 53502,
    childrenUnder5NotInDesertsRural: 83342,
    childrenUnder5InDesertsSuburban: 87777,
    childrenUnder5NotInDesertsSuburban: 290382,
    childrenUnder5InDesertsUrban: 77222,
    childrenUnder5NotInDesertsUrban: 148809,
    textBox: 'Text about California'
  },
  Colorado: {
    state: 'Colorado',
    percentInDesertsAll: 0.7,
    percentInDesertsBlack: 0.67,
    percentInDesertsWhite: 0.48,
    percentInDesertsHispanic: 0.34,
    chidrenUnder5InDesertsRural: 21758,
    childrenUnder5NotInDesertsRural: 53021,
    childrenUnder5InDesertsSuburban: 486175,
    childrenUnder5NotInDesertsSuburban: 651702,
    childrenUnder5InDesertsUrban: 50051,
    childrenUnder5NotInDesertsUrban: 115294,
    textBox: 'Text about Colorado'
  },
  Connecticut: {
    state: 'Connecticut',
    percentInDesertsAll: 0.91,
    percentInDesertsBlack: 0.03,
    percentInDesertsWhite: 0.49,
    percentInDesertsHispanic: 0.35,
    chidrenUnder5InDesertsRural: 56079,
    childrenUnder5NotInDesertsRural: 22135,
    childrenUnder5InDesertsSuburban: 780904,
    childrenUnder5NotInDesertsSuburban: 185073,
    childrenUnder5InDesertsUrban: 43211,
    childrenUnder5NotInDesertsUrban: 76329,
    textBox: 'Text about Connecticut'
  },
  Deleware: {
    state: 'Deleware',
    percentInDesertsAll: 0.55,
    percentInDesertsBlack: 0.69,
    percentInDesertsWhite: 0.34,
    percentInDesertsHispanic: 0.52,
    chidrenUnder5InDesertsRural: 29088,
    childrenUnder5NotInDesertsRural: 54426,
    childrenUnder5InDesertsSuburban: 137083,
    childrenUnder5NotInDesertsSuburban: 609855,
    childrenUnder5InDesertsUrban: 29433,
    childrenUnder5NotInDesertsUrban: 68735,
    textBox: 'Text about Deleware'
  },
  Florida: {
    state: 'Florida',
    percentInDesertsAll: 0.27,
    percentInDesertsBlack: 1,
    percentInDesertsWhite: 0.04,
    percentInDesertsHispanic: 0.02,
    chidrenUnder5InDesertsRural: 56239,
    childrenUnder5NotInDesertsRural: 28096,
    childrenUnder5InDesertsSuburban: 402378,
    childrenUnder5NotInDesertsSuburban: 641870,
    childrenUnder5InDesertsUrban: 70676,
    childrenUnder5NotInDesertsUrban: 24616,
    textBox: 'Text about Florida'
  },
  Georgia: {
    state: 'Georgia',
    percentInDesertsAll: 0.96,
    percentInDesertsBlack: 0.9,
    percentInDesertsWhite: 0.68,
    percentInDesertsHispanic: 0.48,
    chidrenUnder5InDesertsRural: 103743,
    childrenUnder5NotInDesertsRural: 106828,
    childrenUnder5InDesertsSuburban: 221984,
    childrenUnder5NotInDesertsSuburban: 209531,
    childrenUnder5InDesertsUrban: 23314,
    childrenUnder5NotInDesertsUrban: 158649,
    textBox: 'Text about Georgia'
  },
  Iowa: {
    state: 'Iowa',
    percentInDesertsAll: 0.64,
    percentInDesertsBlack: 0.26,
    percentInDesertsWhite: 0.77,
    percentInDesertsHispanic: 0.55,
    chidrenUnder5InDesertsRural: 65711,
    childrenUnder5NotInDesertsRural: 67143,
    childrenUnder5InDesertsSuburban: 837553,
    childrenUnder5NotInDesertsSuburban: 585144,
    childrenUnder5InDesertsUrban: 35247,
    childrenUnder5NotInDesertsUrban: 108746,
    textBox: 'Text about Iowa'
  },
  Illinois: {
    state: 'Illinois',
    percentInDesertsAll: 0.1,
    percentInDesertsBlack: 0.95,
    percentInDesertsWhite: 0.19,
    percentInDesertsHispanic: 0.51,
    chidrenUnder5InDesertsRural: 77024,
    childrenUnder5NotInDesertsRural: 34157,
    childrenUnder5InDesertsSuburban: 374782,
    childrenUnder5NotInDesertsSuburban: 588623,
    childrenUnder5InDesertsUrban: 59702,
    childrenUnder5NotInDesertsUrban: 134516,
    textBox: 'Text about Illinois'
  },
  Kentucky: {
    state: 'Kentucky',
    percentInDesertsAll: 0.75,
    percentInDesertsBlack: 0.75,
    percentInDesertsWhite: 0.35,
    percentInDesertsHispanic: 0.14,
    chidrenUnder5InDesertsRural: 81183,
    childrenUnder5NotInDesertsRural: 28208,
    childrenUnder5InDesertsSuburban: 144902,
    childrenUnder5NotInDesertsSuburban: 384898,
    childrenUnder5InDesertsUrban: 61831,
    childrenUnder5NotInDesertsUrban: 138485,
    textBox: 'Text about Kentucky'
  },
  Michigan: {
    state: 'Michigan',
    percentInDesertsAll: 0.34,
    percentInDesertsBlack: 0.56,
    percentInDesertsWhite: 0.08,
    percentInDesertsHispanic: 0.84,
    chidrenUnder5InDesertsRural: 71226,
    childrenUnder5NotInDesertsRural: 67315,
    childrenUnder5InDesertsSuburban: 822808,
    childrenUnder5NotInDesertsSuburban: 608304,
    childrenUnder5InDesertsUrban: 41176,
    childrenUnder5NotInDesertsUrban: 75405,
    textBox: 'Text about Michigan'
  },
  Minnesota: {
    state: 'Minnesota',
    percentInDesertsAll: 0.08,
    percentInDesertsBlack: 0.05,
    percentInDesertsWhite: 0.17,
    percentInDesertsHispanic: 0.13,
    chidrenUnder5InDesertsRural: 37843,
    childrenUnder5NotInDesertsRural: 25479,
    childrenUnder5InDesertsSuburban: 820410,
    childrenUnder5NotInDesertsSuburban: 612991,
    childrenUnder5InDesertsUrban: 68185,
    childrenUnder5NotInDesertsUrban: 107684,
    textBox: 'Text about Minnesota'
  },
  Missouri: {
    state: 'Missouri',
    percentInDesertsAll: 0.77,
    percentInDesertsBlack: 0.08,
    percentInDesertsWhite: 0.67,
    percentInDesertsHispanic: 0.2,
    chidrenUnder5InDesertsRural: 67620,
    childrenUnder5NotInDesertsRural: 39560,
    childrenUnder5InDesertsSuburban: 436733,
    childrenUnder5NotInDesertsSuburban: 512113,
    childrenUnder5InDesertsUrban: 48395,
    childrenUnder5NotInDesertsUrban: 59218,
    textBox: 'Text about Missouri'
  },
  Mississippi: {
    state: 'Mississippi',
    percentInDesertsAll: 0.98,
    percentInDesertsBlack: 0.6,
    percentInDesertsWhite: 0.92,
    percentInDesertsHispanic: 0.48,
    chidrenUnder5InDesertsRural: 59605,
    childrenUnder5NotInDesertsRural: 34369,
    childrenUnder5InDesertsSuburban: 177351,
    childrenUnder5NotInDesertsSuburban: 463243,
    childrenUnder5InDesertsUrban: 32107,
    childrenUnder5NotInDesertsUrban: 146552,
    textBox: 'Text about Mississippi'
  },
  'New Jersey': {
    state: 'New Jersey',
    percentInDesertsAll: 0.87,
    percentInDesertsBlack: 0.6,
    percentInDesertsWhite: 0.16,
    percentInDesertsHispanic: 0.05,
    chidrenUnder5InDesertsRural: 47752,
    childrenUnder5NotInDesertsRural: 79388,
    childrenUnder5InDesertsSuburban: 357774,
    childrenUnder5NotInDesertsSuburban: 293666,
    childrenUnder5InDesertsUrban: 30018,
    childrenUnder5NotInDesertsUrban: 126701,
    textBox: 'Text about New Jersey'
  },
  'New York': {
    state: 'New York',
    percentInDesertsAll: 0.15,
    percentInDesertsBlack: 0.07,
    percentInDesertsWhite: 0.17,
    percentInDesertsHispanic: 0.61,
    chidrenUnder5InDesertsRural: 72196,
    childrenUnder5NotInDesertsRural: 35301,
    childrenUnder5InDesertsSuburban: 361900,
    childrenUnder5NotInDesertsSuburban: 402989,
    childrenUnder5InDesertsUrban: 44185,
    childrenUnder5NotInDesertsUrban: 142336,
    textBox: 'Text about New York'
  },
  Pennsylvania: {
    state: 'Pennsylvania',
    percentInDesertsAll: 0.23,
    percentInDesertsBlack: 0.75,
    percentInDesertsWhite: 0.17,
    percentInDesertsHispanic: 0.28,
    chidrenUnder5InDesertsRural: 43606,
    childrenUnder5NotInDesertsRural: 76629,
    childrenUnder5InDesertsSuburban: 230365,
    childrenUnder5NotInDesertsSuburban: 364484,
    childrenUnder5InDesertsUrban: 37381,
    childrenUnder5NotInDesertsUrban: 71615,
    textBox: 'Text about Pennsylvania'
  },
  'Rhode Island': {
    state: 'Rhode Island',
    percentInDesertsAll: 0.24,
    percentInDesertsBlack: 0.39,
    percentInDesertsWhite: 0.98,
    percentInDesertsHispanic: 0.3,
    chidrenUnder5InDesertsRural: 63178,
    childrenUnder5NotInDesertsRural: 49801,
    childrenUnder5InDesertsSuburban: 718507,
    childrenUnder5NotInDesertsSuburban: 556368,
    childrenUnder5InDesertsUrban: 59354,
    childrenUnder5NotInDesertsUrban: 80711,
    textBox: 'Text about Rhode Island'
  },
  'South Carolina': {
    state: 'South Carolina',
    percentInDesertsAll: 0.79,
    percentInDesertsBlack: 0.62,
    percentInDesertsWhite: 0.49,
    percentInDesertsHispanic: 0.51,
    chidrenUnder5InDesertsRural: 79265,
    childrenUnder5NotInDesertsRural: 33659,
    childrenUnder5InDesertsSuburban: 317327,
    childrenUnder5NotInDesertsSuburban: 296063,
    childrenUnder5InDesertsUrban: 51959,
    childrenUnder5NotInDesertsUrban: 123661,
    textBox: 'Text about South Carolina'
  },
  'South Dakota': {
    state: 'South Dakota',
    percentInDesertsAll: 0.14,
    percentInDesertsBlack: 0.42,
    percentInDesertsWhite: 0.48,
    percentInDesertsHispanic: 0.73,
    chidrenUnder5InDesertsRural: 66797,
    childrenUnder5NotInDesertsRural: 52414,
    childrenUnder5InDesertsSuburban: 464927,
    childrenUnder5NotInDesertsSuburban: 373853,
    childrenUnder5InDesertsUrban: 43646,
    childrenUnder5NotInDesertsUrban: 65226,
    textBox: 'Text about South Dakota'
  },
  Texas: {
    state: 'Texas',
    percentInDesertsAll: 0.42,
    percentInDesertsBlack: 0.59,
    percentInDesertsWhite: 0.14,
    percentInDesertsHispanic: 0.83,
    chidrenUnder5InDesertsRural: 40417,
    childrenUnder5NotInDesertsRural: 45788,
    childrenUnder5InDesertsSuburban: 458977,
    childrenUnder5NotInDesertsSuburban: 354912,
    childrenUnder5InDesertsUrban: 52077,
    childrenUnder5NotInDesertsUrban: 131410,
    textBox: 'Text about Texas'
  },
  Vermont: {
    state: 'Vermont',
    percentInDesertsAll: 0.9,
    percentInDesertsBlack: 0.49,
    percentInDesertsWhite: 0.82,
    percentInDesertsHispanic: 0.14,
    chidrenUnder5InDesertsRural: 54105,
    childrenUnder5NotInDesertsRural: 49610,
    childrenUnder5InDesertsSuburban: 229892,
    childrenUnder5NotInDesertsSuburban: 326465,
    childrenUnder5InDesertsUrban: 53088,
    childrenUnder5NotInDesertsUrban: 107070,
    textBox: 'Text about Vermont'
  }
};
