/**
 *
 * don't edit this file, it's generated by ./dev/data.ts using the state csv file
 *
 */
/**
 * name of state with data
 */
export type StateName =
  | 'All states'
  | 'Arizona'
  | 'California'
  | 'Colorado'
  | 'Connecticut'
  | 'Delaware'
  | 'Florida'
  | 'Georgia'
  | 'Illinois'
  | 'Iowa'
  | 'Kentucky'
  | 'Michigan'
  | 'Minnesota'
  | 'Mississippi'
  | 'Missouri'
  | 'New Jersey'
  | 'New York'
  | 'Pennsylvania'
  | 'Rhode Island'
  | 'South Carolina'
  | 'South Dakota'
  | 'Texas'
  | 'Vermont';

export const stateList: StateName[] = [
  'All states',
  'Arizona',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Illinois',
  'Iowa',
  'Kentucky',
  'Michigan',
  'Minnesota',
  'Mississippi',
  'Missouri',
  'New Jersey',
  'New York',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Texas',
  'Vermont'
];

export const stateData = {
  'All states': {
    state: 'All states',
    peopleLivingInDeserts: 0.51,
    WhiteInDeserts: 0.49,
    BlackInDeserts: 0.45,
    LatinoInDeserts: 0.57,
    urbanInDeserts: 29667846,
    urbanNondeserts: 22559116,
    suburbanInDeserts: 51551665,
    suburbanNondeserts: 63102291,
    ruralInDeserts: 22092163,
    ruralNondeserts: 15456061,
    InDesertsLowIncome: 0.54,
    InDesertsHighIncome: 0.47,
    abbr: 'US',
    textBox:
      'CAP analyzed the locations of licensed child care providers in 22 states, covering two-thirds of the U.S. population, and found that approximately half of Americans live in "child care deserts." Specifically, this analysis defines child care deserts as neighborhoods or communities that are either lacking any child care options or have so few child care providers that there are more than three children for every licensed child care slot. According to research published by the U.S. Census Bureau, one-third of children under age 5 are regularly in nonrelative care; therefore, in places where there are more than three children for every child care slot, there may be child care waiting lists, unlicensed child care arrangements, or effects on parents\' employment decisions.PPPThis study finds that 58 percent of rural census tracts qualify as child care deserts, while only 44 percent of suburban neighborhoods fit the definition. Urban areas where the median family income is below average also have high rates of child care deserts. Additionally, Hispanic/Latino and American Indian and Alaska Native (AIAN) communities are disproportionately represented in child care deserts, with roughly 60 percent of their combined population living in areas with a low supply of child care. More than 75 percent of the rural AIAN population lives in a child care desert.PPPChild care deserts have, on average, maternal labor force participation rates 3 percentage points lower than communities where there is adequate child care supply. In communities where median family incomes are below the national average, this maternal employment gap is even wider.'
  },
  Arizona: {
    state: 'Arizona',
    peopleLivingInDeserts: 0.48,
    WhiteInDeserts: 0.43,
    BlackInDeserts: 0.53,
    LatinoInDeserts: 0.55,
    urbanInDeserts: 666145,
    urbanNondeserts: 669235,
    suburbanInDeserts: 1863567,
    suburbanNondeserts: 2444969,
    ruralInDeserts: 674270,
    ruralNondeserts: 323742,
    InDesertsLowIncome: 0.57,
    InDesertsHighIncome: 0.37,
    abbr: 'AZ',
    textBox:
      "In Arizona, 48 percent of all residents live in a child care desert. However, 55 percent of Arizona's Hispanic/Latino population lives in a child care desert. Child care supply is especially low in Arizona's rural areas, where 68 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Arizona, the maternal labor force participation rate in child care deserts is 2.5 percentage points lower than it is in neighborhoods with adequate licensed child care.  ",
    bounds: [
      31.3321762084961,
      37.0042610168457,
      -114.818359375,
      -109.045196533203
    ],
    center: [-111.7632755, 34.395342]
  },
  California: {
    state: 'California',
    peopleLivingInDeserts: 0.62,
    WhiteInDeserts: 0.57,
    BlackInDeserts: 0.64,
    LatinoInDeserts: 0.69,
    urbanInDeserts: 11146752,
    urbanNondeserts: 6665636,
    suburbanInDeserts: 10669507,
    suburbanNondeserts: 6815747,
    ruralInDeserts: 1991855,
    ruralNondeserts: 1131966,
    InDesertsLowIncome: 0.7,
    InDesertsHighIncome: 0.56,
    abbr: 'CA',
    textBox:
      "In California, 62 percent of all residents live in a child care desert. However, 69 percent of California's Hispanic/Latino population lives in a child care desert. Child care supply is especially low in California's rural areas, where 64 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In California, the maternal labor force participation rate in child care deserts is 2.9 percentage points lower than it is in neighborhoods with adequate licensed child care. Note: The California Department of Social Services does not provide addresses of family child care providers, though it does include their ZIP codes. These child care providers are not shown on the map, but their capacity data have been included at the census tract level.  ",
    bounds: [
      32.5295219421387,
      42.0095024108887,
      -124.482009887695,
      -114.13077545166
    ],
    center: [-118.7559974, 36.7014631]
  },
  Colorado: {
    state: 'Colorado',
    peopleLivingInDeserts: 0.3,
    WhiteInDeserts: 0.27,
    BlackInDeserts: 0.37,
    LatinoInDeserts: 0.38,
    urbanInDeserts: 439959,
    urbanNondeserts: 800025,
    suburbanInDeserts: 818705,
    suburbanNondeserts: 2196763,
    ruralInDeserts: 314663,
    ruralNondeserts: 708791,
    InDesertsLowIncome: 0.42,
    InDesertsHighIncome: 0.23,
    abbr: 'CO',
    textBox:
      "In Colorado, 30 percent of all residents live in a child care desert. However, 38 percent of Colorado's Hispanic/Latino population lives in a child care desert. Child care supply is especially low in Colorado's urban areas, where 35 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Colorado, the maternal labor force participation rate in child care deserts is 3.4 percentage points lower than it is in neighborhoods with adequate licensed child care.  ",
    bounds: [
      36.9924240112305,
      41.0023612976074,
      -109.060256958008,
      -102.041580200195
    ],
    center: [-105.6077167, 38.7251776]
  },
  Connecticut: {
    state: 'Connecticut',
    peopleLivingInDeserts: 0.44,
    WhiteInDeserts: 0.41,
    BlackInDeserts: 0.52,
    LatinoInDeserts: 0.51,
    urbanInDeserts: 364741,
    urbanNondeserts: 325022,
    suburbanInDeserts: 1039247,
    suburbanNondeserts: 1537965,
    ruralInDeserts: 162349,
    ruralNondeserts: 163898,
    InDesertsLowIncome: 0.54,
    InDesertsHighIncome: 0.41,
    abbr: 'CT',
    textBox:
      "In Connecticut, 44 percent of all residents live in a child care desert. However, 51 percent of Connecticut's Hispanic/Latino population lives in a child care desert. Child care supply is especially low in Connecticut's rural areas, where 50 percent of residents live in areas without enough licensed child care providers. Also, lower-income communities in Connecticut are 30 percent more likely to be child care deserts than higher-income areas.",
    bounds: [
      40.9667053222656,
      42.0505905151367,
      -73.7277755737305,
      -71.7869873046875
    ],
    center: [-72.5982114, 41.493929]
  },
  Delaware: {
    state: 'Delaware',
    peopleLivingInDeserts: 0.25,
    WhiteInDeserts: 0.26,
    BlackInDeserts: 0.22,
    LatinoInDeserts: 0.26,
    urbanInDeserts: 15893,
    urbanNondeserts: 73617,
    suburbanInDeserts: 172931,
    suburbanNondeserts: 491908,
    ruralInDeserts: 44356,
    ruralNondeserts: 127749,
    InDesertsLowIncome: 0.29,
    InDesertsHighIncome: 0.23,
    abbr: 'DE',
    textBox:
      "In Delaware, 25 percent of all residents live in a child care desert. Child care deserts are especially rare in Delaware's urban areas, where only 18 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Delaware, the maternal labor force participation rate in child care deserts is 2.9 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      38.4511260986328,
      39.8394355773926,
      -75.7890472412109,
      -74.9846343994141
    ],
    center: [-75.4013315, 38.6920451]
  },
  Florida: {
    state: 'Florida',
    peopleLivingInDeserts: 0.38,
    WhiteInDeserts: 0.39,
    BlackInDeserts: 0.32,
    LatinoInDeserts: 0.37,
    urbanInDeserts: 1340608,
    urbanNondeserts: 2131929,
    suburbanInDeserts: 4952869,
    suburbanNondeserts: 9047888,
    ruralInDeserts: 1109887,
    ruralNondeserts: 1062591,
    InDesertsLowIncome: 0.38,
    InDesertsHighIncome: 0.38,
    abbr: 'FL',
    textBox:
      "In Florida, 38 percent of all residents live in a child care desert. Child care supply is especially low in Florida's rural areas, where 51 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Florida, the maternal labor force participation rate in child care deserts is 1 percentage point lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      24.3963069915771,
      31.0009689331055,
      -87.6349029541016,
      -79.9743041992188
    ],
    center: [-81.4639835, 27.7567667]
  },
  Georgia: {
    state: 'Georgia',
    peopleLivingInDeserts: 0.45,
    WhiteInDeserts: 0.48,
    BlackInDeserts: 0.39,
    LatinoInDeserts: 0.49,
    urbanInDeserts: 172783,
    urbanNondeserts: 175336,
    suburbanInDeserts: 2526108,
    suburbanNondeserts: 4244961,
    ruralInDeserts: 1765473,
    ruralNondeserts: 1122032,
    InDesertsLowIncome: 0.49,
    InDesertsHighIncome: 0.39,
    abbr: 'GA',
    textBox:
      "In Georgia, 45 percent of all residents live in a child care desert. However, 49 percent of Georgia's Hispanic/Latino population lives in a child care desert. Child care supply is especially low in Georgia's rural areas, where 61 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Georgia, the maternal labor force participation rate in child care deserts is 1.6 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      30.3557567596436,
      35.0008316040039,
      -85.6051712036133,
      -80.7514266967773
    ],
    center: [-83.1137366, 32.3293809]
  },
  Illinois: {
    state: 'Illinois',
    peopleLivingInDeserts: 0.59,
    WhiteInDeserts: 0.6,
    BlackInDeserts: 0.46,
    LatinoInDeserts: 0.68,
    urbanInDeserts: 2298570,
    urbanNondeserts: 1451048,
    suburbanInDeserts: 3944127,
    suburbanNondeserts: 3239537,
    ruralInDeserts: 1341740,
    ruralNondeserts: 598739,
    InDesertsLowIncome: 0.6,
    InDesertsHighIncome: 0.59,
    abbr: 'IL',
    textBox:
      "In Illinois, 59 percent of all residents live in a child care desert. However, 68 percent of Illinois' Hispanic/Latino population lives in a child care desert. Child care supply is especially low in Illinois' rural areas, where 69 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Illinois, the maternal labor force participation rate in child care deserts is 1.8 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      36.9701309204102,
      42.5083045959473,
      -91.513053894043,
      -87.0199203491211
    ],
    center: [-89.4339809, 40.0796319]
  },
  Iowa: {
    state: 'Iowa',
    peopleLivingInDeserts: 0.24,
    WhiteInDeserts: 0.25,
    BlackInDeserts: 0.18,
    LatinoInDeserts: 0.24,
    urbanInDeserts: 35193,
    urbanNondeserts: 94209,
    suburbanInDeserts: 249051,
    suburbanNondeserts: 1463600,
    ruralInDeserts: 466296,
    ruralNondeserts: 785177,
    InDesertsLowIncome: 0.25,
    InDesertsHighIncome: 0.24,
    abbr: 'IA',
    textBox:
      "In Iowa, 24 percent of all residents live in a child care desert. However, child care supply is especially low in Iowa's rural areas, where 37 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Iowa, the maternal labor force participation rate in child care deserts is 2.2 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      40.3755989074707,
      43.5011367797852,
      -96.6397171020508,
      -90.1400604248047
    ],
    center: [-93.3122705, 41.9216734]
  },
  Kentucky: {
    state: 'Kentucky',
    peopleLivingInDeserts: 0.5,
    WhiteInDeserts: 0.52,
    BlackInDeserts: 0.37,
    LatinoInDeserts: 0.45,
    urbanInDeserts: 132873,
    urbanNondeserts: 135704,
    suburbanInDeserts: 636860,
    suburbanNondeserts: 1422555,
    ruralInDeserts: 1434888,
    ruralNondeserts: 634473,
    InDesertsLowIncome: 0.57,
    InDesertsHighIncome: 0.38,
    abbr: 'KY',
    textBox:
      "In Kentucky, 50 percent of all residents live in a child care desert. Child care supply is especially low in Kentucky's rural areas, where 69 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Kentucky, the maternal labor force participation rate in child care deserts is 5.4 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      36.4967155456543,
      39.1474609375,
      -89.5715103149414,
      -81.9645385742188
    ],
    center: [-85.1551411, 37.5726028]
  },
  Michigan: {
    state: 'Michigan',
    peopleLivingInDeserts: 0.46,
    WhiteInDeserts: 0.46,
    BlackInDeserts: 0.5,
    LatinoInDeserts: 0.48,
    urbanInDeserts: 634289,
    urbanNondeserts: 542089,
    suburbanInDeserts: 2593247,
    suburbanNondeserts: 3425631,
    ruralInDeserts: 1359929,
    ruralNondeserts: 1345386,
    InDesertsLowIncome: 0.48,
    InDesertsHighIncome: 0.45,
    abbr: 'MI',
    textBox:
      "In Michigan, 46 percent of all residents live in a child care desert. However, 50 percent of Michigan's non-Hispanic, black/African American population lives in a child care desert. Child care supply is especially low in Michigan's rural areas, where 50 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Michigan, the maternal labor force participation rate in child care deserts is 1.5 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      41.6960868835449,
      48.3060646057129,
      -90.4186248779297,
      -82.122802734375
    ],
    center: [-84.6824346, 43.6211955]
  },
  Minnesota: {
    state: 'Minnesota',
    peopleLivingInDeserts: 0.26,
    WhiteInDeserts: 0.24,
    BlackInDeserts: 0.36,
    LatinoInDeserts: 0.32,
    urbanInDeserts: 299931,
    urbanNondeserts: 362121,
    suburbanInDeserts: 675989,
    suburbanNondeserts: 2524810,
    ruralInDeserts: 430588,
    ruralNondeserts: 1125732,
    InDesertsLowIncome: 0.33,
    InDesertsHighIncome: 0.23,
    abbr: 'MN',
    textBox:
      "In Minnesota, 26 percent of all residents live in a child care desert. However, 32 percent of Minnesota's Hispanic/Latino population lives in a child care desert. Child care supply is especially low in Minnesota's urban areas, where 45 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Minnesota, the maternal labor force participation rate in child care deserts is 2.5 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      43.4994277954102,
      49.3844909667969,
      -97.2392654418945,
      -89.4833831787109
    ],
    center: [-94.6113288, 45.9896587]
  },
  Mississippi: {
    state: 'Mississippi',
    peopleLivingInDeserts: 0.41,
    WhiteInDeserts: 0.46,
    BlackInDeserts: 0.35,
    LatinoInDeserts: 0.41,
    urbanInDeserts: 0,
    urbanNondeserts: 0,
    suburbanInDeserts: 364974,
    suburbanNondeserts: 1026588,
    ruralInDeserts: 870794,
    ruralNondeserts: 725725,
    InDesertsLowIncome: 0.45,
    InDesertsHighIncome: 0.29,
    abbr: 'MS',
    textBox:
      "In Mississippi, 41 percent of all residents live in a child care desert. Child care supply is especially low in Mississippi's rural areas, where 55 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Mississippi, the maternal labor force participation rate in child care deserts is 3 percentage points lower than it is in neighborhoods with adequate licensed child care. Note: Mississippi does not provide public data on family child care providers.",
    bounds: [
      30.1477890014648,
      34.9960556030273,
      -91.6550140380859,
      -88.0980072021484
    ],
    center: [-89.7348497, 32.9715645]
  },
  Missouri: {
    state: 'Missouri',
    peopleLivingInDeserts: 0.55,
    WhiteInDeserts: 0.56,
    BlackInDeserts: 0.48,
    LatinoInDeserts: 0.61,
    urbanInDeserts: 238088,
    urbanNondeserts: 186953,
    suburbanInDeserts: 1723452,
    suburbanNondeserts: 1979649,
    ruralInDeserts: 1365316,
    ruralNondeserts: 551990,
    InDesertsLowIncome: 0.6,
    InDesertsHighIncome: 0.49,
    abbr: 'MO',
    textBox:
      "In Missouri, 55 percent of all residents live in a child care desert. However, 61 percent of Missouri's Hispanic/Latino population lives in a child care desert. Child care supply is especially low in Missouri's rural areas, where 71 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Missouri, the maternal labor force participation rate in child care deserts is 1.5 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      35.9956817626953,
      40.6136360168457,
      -95.7741470336914,
      -89.0988388061523
    ],
    center: [-92.5617875, 38.7604815]
  },
  'New Jersey': {
    state: 'New Jersey',
    peopleLivingInDeserts: 0.48,
    WhiteInDeserts: 0.47,
    BlackInDeserts: 0.52,
    LatinoInDeserts: 0.53,
    urbanInDeserts: 1632040,
    urbanNondeserts: 1400324,
    suburbanInDeserts: 2403160,
    suburbanNondeserts: 2963609,
    ruralInDeserts: 255525,
    ruralNondeserts: 249755,
    InDesertsLowIncome: 0.56,
    InDesertsHighIncome: 0.46,
    abbr: 'NJ',
    textBox:
      "In New Jersey, 48 percent of all residents live in a child care desert. However, 53 percent of New Jersey's Hispanic/Latino population lives in a child care desert. Child care supply is especially low in New Jersey's urban areas, where 54 percent of residents live in areas without enough licensed child care providers. Also, lower-income communities in New Jersey are 20 percent more likely to be child care deserts than higher-income areas. Note: New Jersey does not provide public data on family child care providers.",
    bounds: [
      38.7887535095215,
      41.3574256896973,
      -75.5633926391602,
      -73.8850555419922
    ],
    center: [-74.4041622, 40.0757384]
  },
  'New York': {
    state: 'New York',
    peopleLivingInDeserts: 0.61,
    WhiteInDeserts: 0.65,
    BlackInDeserts: 0.53,
    LatinoInDeserts: 0.57,
    urbanInDeserts: 6344297,
    urbanNondeserts: 4415243,
    suburbanInDeserts: 3652666,
    suburbanNondeserts: 2533065,
    ruralInDeserts: 2015384,
    ruralNondeserts: 712519,
    InDesertsLowIncome: 0.61,
    InDesertsHighIncome: 0.62,
    abbr: 'NY',
    textBox:
      "In New York, 61 percent of all residents live in a child care desert. However, child care supply is especially low in New York's rural areas, where 74 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In New York, the maternal labor force participation rate in child care deserts is 1.1 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      40.4773979187012,
      45.0158615112305,
      -79.7625122070312,
      -71.8527069091797
    ],
    center: [-75.8449946, 43.1561681]
  },
  Pennsylvania: {
    state: 'Pennsylvania',
    peopleLivingInDeserts: 0.59,
    WhiteInDeserts: 0.6,
    BlackInDeserts: 0.49,
    LatinoInDeserts: 0.59,
    urbanInDeserts: 1707849,
    urbanNondeserts: 1419045,
    suburbanInDeserts: 3682086,
    suburbanNondeserts: 3075619,
    ruralInDeserts: 2110722,
    ruralNondeserts: 784238,
    InDesertsLowIncome: 0.62,
    InDesertsHighIncome: 0.57,
    abbr: 'PA',
    textBox:
      "In Pennsylvania, 59 percent of all residents live in a child care desert. However, child care supply is especially low in Pennsylvania's rural areas, where 73 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Pennsylvania, the maternal labor force participation rate in child care deserts is 1.6 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      39.7197647094727,
      42.5146903991699,
      -80.5210876464844,
      -74.6894989013672
    ],
    center: [-77.7278831, 40.9699889]
  },
  'Rhode Island': {
    state: 'Rhode Island',
    peopleLivingInDeserts: 0.5,
    WhiteInDeserts: 0.5,
    BlackInDeserts: 0.51,
    LatinoInDeserts: 0.52,
    urbanInDeserts: 204929,
    urbanNondeserts: 154520,
    suburbanInDeserts: 279895,
    suburbanNondeserts: 334730,
    ruralInDeserts: 44918,
    ruralNondeserts: 34669,
    InDesertsLowIncome: 0.5,
    InDesertsHighIncome: 0.51,
    abbr: 'RI',
    textBox:
      "In Rhode Island, 50 percent of all residents live in a child care desert. However, child care supply is especially low in Rhode Island's rural areas, where 56 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Rhode Island, the maternal labor force participation rate in child care deserts is 2.4 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      41.055534362793,
      42.018856048584,
      -71.9070053100586,
      -71.1204681396484
    ],
    center: [-71.5992372, 41.7962409]
  },
  'South Carolina': {
    state: 'South Carolina',
    peopleLivingInDeserts: 0.47,
    WhiteInDeserts: 0.5,
    BlackInDeserts: 0.39,
    LatinoInDeserts: 0.5,
    urbanInDeserts: 27107,
    urbanNondeserts: 28137,
    suburbanInDeserts: 1415210,
    suburbanNondeserts: 1613488,
    ruralInDeserts: 789166,
    ruralNondeserts: 904468,
    InDesertsLowIncome: 0.42,
    InDesertsHighIncome: 0.56,
    abbr: 'SC',
    textBox:
      "In South Carolina, 47 percent of all residents live in a child care desert. However, 50 percent of South Carolina's Hispanic/Latino population lives in a child care desert. CAP finds that child care deserts are associated with fewer mothers in the workforce. In South Carolina, the maternal labor force participation rate in child care deserts is 1.3 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      32.0333099365234,
      35.2155418395996,
      -83.35400390625,
      -78.4992980957031
    ],
    center: [-80.4363743, 33.6874388]
  },
  'South Dakota': {
    state: 'South Dakota',
    peopleLivingInDeserts: 0.47,
    WhiteInDeserts: 0.45,
    BlackInDeserts: 0.38,
    LatinoInDeserts: 0.51,
    urbanInDeserts: 2590,
    urbanNondeserts: 12966,
    suburbanInDeserts: 133375,
    suburbanNondeserts: 240889,
    ruralInDeserts: 263858,
    ruralNondeserts: 189512,
    InDesertsLowIncome: 0.53,
    InDesertsHighIncome: 0.43,
    abbr: 'SD',
    textBox:
      "In South Dakota, 47 percent of all residents live in a child care desert. However, 51 percent of South Dakota's Hispanic/Latino population lives in a child care desert. Child care supply is especially low in South Dakota's rural areas, where 58 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In South Dakota, the maternal labor force participation rate in child care deserts is 2.2 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      42.4798889160156,
      45.9454536437988,
      -104.05770111084,
      -96.4363327026367
    ],
    center: [-100.348761, 44.6471761]
  },
  Texas: {
    state: 'Texas',
    peopleLivingInDeserts: 0.48,
    WhiteInDeserts: 0.45,
    BlackInDeserts: 0.45,
    LatinoInDeserts: 0.54,
    urbanInDeserts: 1960582,
    urbanNondeserts: 1494639,
    suburbanInDeserts: 7706409,
    suburbanNondeserts: 10344347,
    ruralInDeserts: 3098665,
    ruralNondeserts: 1933971,
    InDesertsLowIncome: 0.56,
    InDesertsHighIncome: 0.4,
    abbr: 'TX',
    textBox:
      "In Texas, 48 percent of all residents live in a child care desert. However, 54 percent of Texas' Hispanic/Latino population lives in a child care desert. Child care supply is especially low in Texas' rural areas, where 62 percent of residents live in areas without enough licensed child care providers. CAP finds that child care deserts are associated with fewer mothers in the workforce. In Texas, the maternal labor force participation rate in child care deserts is 3.3 percentage points lower than it is in neighborhoods with adequate licensed child care.",
    bounds: [
      25.8370609283447,
      36.5007057189941,
      -106.645652770996,
      -93.5078201293945
    ],
    center: [-99.5120986, 31.8160381]
  },
  Vermont: {
    state: 'Vermont',
    peopleLivingInDeserts: 0.37,
    WhiteInDeserts: 0.37,
    BlackInDeserts: 0.41,
    LatinoInDeserts: 0.32,
    urbanInDeserts: 2627,
    urbanNondeserts: 21316,
    suburbanInDeserts: 48230,
    suburbanNondeserts: 133972,
    ruralInDeserts: 181521,
    ruralNondeserts: 238938,
    InDesertsLowIncome: 0.35,
    InDesertsHighIncome: 0.38,
    abbr: 'VT',
    textBox:
      "In Vermont, 37 percent of all residents live in a child care desert. However, child care supply is particularly low in Vermont's rural areas, where 43 percent of residents live in areas without enough licensed child care providers.",
    bounds: [
      42.7269325256348,
      45.0166664123535,
      -73.437744140625,
      -71.4653549194336
    ],
    center: [-72.5002608, 44.5990718]
  }
};
