/**
 *
 * don't edit this file, it's generated by ./dev/data.ts using the state csv file
 *
 */
/**
 * name of state with data
 */
export type StateName =
  | 'All states'
  | 'Arizona'
  | 'California'
  | 'Colorado'
  | 'Connecticut'
  | 'Delaware'
  | 'Florida'
  | 'Georgia'
  | 'Iowa'
  | 'Illinois'
  | 'Kentucky'
  | 'Michigan'
  | 'Minnesota'
  | 'Missouri'
  | 'Mississippi'
  | 'New Jersey'
  | 'New York'
  | 'Pennsylvania'
  | 'Rhode Island'
  | 'South Carolina'
  | 'South Dakota'
  | 'Texas'
  | 'Vermont';

export const stateList: StateName[] = [
  'All states',
  'Arizona',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Iowa',
  'Illinois',
  'Kentucky',
  'Michigan',
  'Minnesota',
  'Missouri',
  'Mississippi',
  'New Jersey',
  'New York',
  'Pennsylvania',
  'Rhode Island',
  'South Carolina',
  'South Dakota',
  'Texas',
  'Vermont'
];

export const stateData = {
  'All states': {
    state: 'All states',
    percentInDesertsAll: 0.397,
    percentInDesertsBlack: 0.306,
    percentInDesertsWhite: 0.402,
    percentInDesertsHispanic: 0.544,
    chidrenUnder5InDesertsRural: 541690,
    childrenUnder5NotInDesertsRural: 436904,
    childrenUnder5InDesertsSuburban: 935144,
    childrenUnder5NotInDesertsSuburban: 1696870,
    childrenUnder5InDesertsUrban: 372111,
    childrenUnder5NotInDesertsUrban: 382846,
    textBox: '',
    abbr: 'US'
  },
  Arizona: {
    state: 'Arizona',
    percentInDesertsAll: 0.33,
    percentInDesertsBlack: 0.03,
    percentInDesertsWhite: 0.87,
    percentInDesertsHispanic: 0.51,
    chidrenUnder5InDesertsRural: 72025,
    childrenUnder5NotInDesertsRural: 166450,
    childrenUnder5InDesertsSuburban: 916931,
    childrenUnder5NotInDesertsSuburban: 679831,
    childrenUnder5InDesertsUrban: 80514,
    childrenUnder5NotInDesertsUrban: 197435,
    textBox: 'Text about Arizona',
    abbr: 'AZ',
    bounds: [
      31.3321762084961,
      37.0042610168457,
      -114.818359375,
      -109.045196533203
    ],
    center: [-111.7632755, 34.395342]
  },
  California: {
    state: 'California',
    percentInDesertsAll: 0.16,
    percentInDesertsBlack: 0.2,
    percentInDesertsWhite: 0.85,
    percentInDesertsHispanic: 0.02,
    chidrenUnder5InDesertsRural: 53502,
    childrenUnder5NotInDesertsRural: 83342,
    childrenUnder5InDesertsSuburban: 87777,
    childrenUnder5NotInDesertsSuburban: 290382,
    childrenUnder5InDesertsUrban: 77222,
    childrenUnder5NotInDesertsUrban: 148809,
    textBox: 'Text about California',
    abbr: 'CA',
    bounds: [
      32.5295219421387,
      42.0095024108887,
      -124.482009887695,
      -114.13077545166
    ],
    center: [-118.7559974, 36.7014631]
  },
  Colorado: {
    state: 'Colorado',
    percentInDesertsAll: 0.7,
    percentInDesertsBlack: 0.67,
    percentInDesertsWhite: 0.48,
    percentInDesertsHispanic: 0.34,
    chidrenUnder5InDesertsRural: 21758,
    childrenUnder5NotInDesertsRural: 53021,
    childrenUnder5InDesertsSuburban: 486175,
    childrenUnder5NotInDesertsSuburban: 651702,
    childrenUnder5InDesertsUrban: 50051,
    childrenUnder5NotInDesertsUrban: 115294,
    textBox: 'Text about Colorado',
    abbr: 'CO',
    bounds: [
      36.9924240112305,
      41.0023612976074,
      -109.060256958008,
      -102.041580200195
    ],
    center: [-105.6077167, 38.7251776]
  },
  Connecticut: {
    state: 'Connecticut',
    percentInDesertsAll: 0.91,
    percentInDesertsBlack: 0.03,
    percentInDesertsWhite: 0.49,
    percentInDesertsHispanic: 0.35,
    chidrenUnder5InDesertsRural: 56079,
    childrenUnder5NotInDesertsRural: 22135,
    childrenUnder5InDesertsSuburban: 780904,
    childrenUnder5NotInDesertsSuburban: 185073,
    childrenUnder5InDesertsUrban: 43211,
    childrenUnder5NotInDesertsUrban: 76329,
    textBox: 'Text about Connecticut',
    abbr: 'CT',
    bounds: [
      40.9667053222656,
      42.0505905151367,
      -73.7277755737305,
      -71.7869873046875
    ],
    center: [-72.5982114, 41.493929]
  },
  Delaware: {
    state: 'Delaware',
    percentInDesertsAll: 0.55,
    percentInDesertsBlack: 0.69,
    percentInDesertsWhite: 0.34,
    percentInDesertsHispanic: 0.52,
    chidrenUnder5InDesertsRural: 29088,
    childrenUnder5NotInDesertsRural: 54426,
    childrenUnder5InDesertsSuburban: 137083,
    childrenUnder5NotInDesertsSuburban: 609855,
    childrenUnder5InDesertsUrban: 29433,
    childrenUnder5NotInDesertsUrban: 68735,
    textBox: 'Text about Deleware',
    abbr: 'DE',
    bounds: [
      38.4511260986328,
      39.8394355773926,
      -75.7890472412109,
      -74.9846343994141
    ],
    center: [-75.4013315, 38.6920451]
  },
  Florida: {
    state: 'Florida',
    percentInDesertsAll: 0.27,
    percentInDesertsBlack: 1,
    percentInDesertsWhite: 0.04,
    percentInDesertsHispanic: 0.02,
    chidrenUnder5InDesertsRural: 56239,
    childrenUnder5NotInDesertsRural: 28096,
    childrenUnder5InDesertsSuburban: 402378,
    childrenUnder5NotInDesertsSuburban: 641870,
    childrenUnder5InDesertsUrban: 70676,
    childrenUnder5NotInDesertsUrban: 24616,
    textBox: 'Text about Florida',
    abbr: 'FL',
    bounds: [
      24.3963069915771,
      31.0009689331055,
      -87.6349029541016,
      -79.9743041992188
    ],
    center: [-81.4639835, 27.7567667]
  },
  Georgia: {
    state: 'Georgia',
    percentInDesertsAll: 0.96,
    percentInDesertsBlack: 0.9,
    percentInDesertsWhite: 0.68,
    percentInDesertsHispanic: 0.48,
    chidrenUnder5InDesertsRural: 103743,
    childrenUnder5NotInDesertsRural: 106828,
    childrenUnder5InDesertsSuburban: 221984,
    childrenUnder5NotInDesertsSuburban: 209531,
    childrenUnder5InDesertsUrban: 23314,
    childrenUnder5NotInDesertsUrban: 158649,
    textBox: 'Text about Georgia',
    abbr: 'GA',
    bounds: [
      30.3557567596436,
      35.0008316040039,
      -85.6051712036133,
      -80.7514266967773
    ],
    center: [-83.1137366, 32.3293809]
  },
  Iowa: {
    state: 'Iowa',
    percentInDesertsAll: 0.64,
    percentInDesertsBlack: 0.26,
    percentInDesertsWhite: 0.77,
    percentInDesertsHispanic: 0.55,
    chidrenUnder5InDesertsRural: 65711,
    childrenUnder5NotInDesertsRural: 67143,
    childrenUnder5InDesertsSuburban: 837553,
    childrenUnder5NotInDesertsSuburban: 585144,
    childrenUnder5InDesertsUrban: 35247,
    childrenUnder5NotInDesertsUrban: 108746,
    textBox: 'Text about Iowa',
    abbr: 'IA',
    bounds: [
      40.3755989074707,
      43.5011367797852,
      -96.6397171020508,
      -90.1400604248047
    ],
    center: [-93.3122705, 41.9216734]
  },
  Illinois: {
    state: 'Illinois',
    percentInDesertsAll: 0.1,
    percentInDesertsBlack: 0.95,
    percentInDesertsWhite: 0.19,
    percentInDesertsHispanic: 0.51,
    chidrenUnder5InDesertsRural: 77024,
    childrenUnder5NotInDesertsRural: 34157,
    childrenUnder5InDesertsSuburban: 374782,
    childrenUnder5NotInDesertsSuburban: 588623,
    childrenUnder5InDesertsUrban: 59702,
    childrenUnder5NotInDesertsUrban: 134516,
    textBox: 'Text about Illinois',
    abbr: 'IL',
    bounds: [
      36.9701309204102,
      42.5083045959473,
      -91.513053894043,
      -87.0199203491211
    ],
    center: [-89.4339809, 40.0796319]
  },
  Kentucky: {
    state: 'Kentucky',
    percentInDesertsAll: 0.75,
    percentInDesertsBlack: 0.75,
    percentInDesertsWhite: 0.35,
    percentInDesertsHispanic: 0.14,
    chidrenUnder5InDesertsRural: 81183,
    childrenUnder5NotInDesertsRural: 28208,
    childrenUnder5InDesertsSuburban: 144902,
    childrenUnder5NotInDesertsSuburban: 384898,
    childrenUnder5InDesertsUrban: 61831,
    childrenUnder5NotInDesertsUrban: 138485,
    textBox: 'Text about Kentucky',
    abbr: 'KY',
    bounds: [
      36.4967155456543,
      39.1474609375,
      -89.5715103149414,
      -81.9645385742188
    ],
    center: [-85.1551411, 37.5726028]
  },
  Michigan: {
    state: 'Michigan',
    percentInDesertsAll: 0.34,
    percentInDesertsBlack: 0.56,
    percentInDesertsWhite: 0.08,
    percentInDesertsHispanic: 0.84,
    chidrenUnder5InDesertsRural: 71226,
    childrenUnder5NotInDesertsRural: 67315,
    childrenUnder5InDesertsSuburban: 822808,
    childrenUnder5NotInDesertsSuburban: 608304,
    childrenUnder5InDesertsUrban: 41176,
    childrenUnder5NotInDesertsUrban: 75405,
    textBox: 'Text about Michigan',
    abbr: 'MI',
    bounds: [
      41.6960868835449,
      48.3060646057129,
      -90.4186248779297,
      -82.122802734375
    ],
    center: [-84.6824346, 43.6211955]
  },
  Minnesota: {
    state: 'Minnesota',
    percentInDesertsAll: 0.08,
    percentInDesertsBlack: 0.05,
    percentInDesertsWhite: 0.17,
    percentInDesertsHispanic: 0.13,
    chidrenUnder5InDesertsRural: 37843,
    childrenUnder5NotInDesertsRural: 25479,
    childrenUnder5InDesertsSuburban: 820410,
    childrenUnder5NotInDesertsSuburban: 612991,
    childrenUnder5InDesertsUrban: 68185,
    childrenUnder5NotInDesertsUrban: 107684,
    textBox: 'Text about Minnesota',
    abbr: 'MN',
    bounds: [
      43.4994277954102,
      49.3844909667969,
      -97.2392654418945,
      -89.4833831787109
    ],
    center: [-94.6113288, 45.9896587]
  },
  Missouri: {
    state: 'Missouri',
    percentInDesertsAll: 0.77,
    percentInDesertsBlack: 0.08,
    percentInDesertsWhite: 0.67,
    percentInDesertsHispanic: 0.2,
    chidrenUnder5InDesertsRural: 67620,
    childrenUnder5NotInDesertsRural: 39560,
    childrenUnder5InDesertsSuburban: 436733,
    childrenUnder5NotInDesertsSuburban: 512113,
    childrenUnder5InDesertsUrban: 48395,
    childrenUnder5NotInDesertsUrban: 59218,
    textBox: 'Text about Missouri',
    abbr: 'MO',
    bounds: [
      35.9956817626953,
      40.6136360168457,
      -95.7741470336914,
      -89.0988388061523
    ],
    center: [-92.5617875, 38.7604815]
  },
  Mississippi: {
    state: 'Mississippi',
    percentInDesertsAll: 0.98,
    percentInDesertsBlack: 0.6,
    percentInDesertsWhite: 0.92,
    percentInDesertsHispanic: 0.48,
    chidrenUnder5InDesertsRural: 59605,
    childrenUnder5NotInDesertsRural: 34369,
    childrenUnder5InDesertsSuburban: 177351,
    childrenUnder5NotInDesertsSuburban: 463243,
    childrenUnder5InDesertsUrban: 32107,
    childrenUnder5NotInDesertsUrban: 146552,
    textBox: 'Text about Mississippi',
    abbr: 'MS',
    bounds: [
      30.1477890014648,
      34.9960556030273,
      -91.6550140380859,
      -88.0980072021484
    ],
    center: [-89.7348497, 32.9715645]
  },
  'New Jersey': {
    state: 'New Jersey',
    percentInDesertsAll: 0.87,
    percentInDesertsBlack: 0.6,
    percentInDesertsWhite: 0.16,
    percentInDesertsHispanic: 0.05,
    chidrenUnder5InDesertsRural: 47752,
    childrenUnder5NotInDesertsRural: 79388,
    childrenUnder5InDesertsSuburban: 357774,
    childrenUnder5NotInDesertsSuburban: 293666,
    childrenUnder5InDesertsUrban: 30018,
    childrenUnder5NotInDesertsUrban: 126701,
    textBox: 'Text about New Jersey',
    abbr: 'NJ',
    bounds: [
      38.7887535095215,
      41.3574256896973,
      -75.5633926391602,
      -73.8850555419922
    ],
    center: [-74.4041622, 40.0757384]
  },
  'New York': {
    state: 'New York',
    percentInDesertsAll: 0.15,
    percentInDesertsBlack: 0.07,
    percentInDesertsWhite: 0.17,
    percentInDesertsHispanic: 0.61,
    chidrenUnder5InDesertsRural: 72196,
    childrenUnder5NotInDesertsRural: 35301,
    childrenUnder5InDesertsSuburban: 361900,
    childrenUnder5NotInDesertsSuburban: 402989,
    childrenUnder5InDesertsUrban: 44185,
    childrenUnder5NotInDesertsUrban: 142336,
    textBox: 'Text about New York',
    abbr: 'NY',
    bounds: [
      40.4773979187012,
      45.0158615112305,
      -79.7625122070312,
      -71.8527069091797
    ],
    center: [-75.8449946, 43.1561681]
  },
  Pennsylvania: {
    state: 'Pennsylvania',
    percentInDesertsAll: 0.23,
    percentInDesertsBlack: 0.75,
    percentInDesertsWhite: 0.17,
    percentInDesertsHispanic: 0.28,
    chidrenUnder5InDesertsRural: 43606,
    childrenUnder5NotInDesertsRural: 76629,
    childrenUnder5InDesertsSuburban: 230365,
    childrenUnder5NotInDesertsSuburban: 364484,
    childrenUnder5InDesertsUrban: 37381,
    childrenUnder5NotInDesertsUrban: 71615,
    textBox: 'Text about Pennsylvania',
    abbr: 'PA',
    bounds: [
      39.7197647094727,
      42.5146903991699,
      -80.5210876464844,
      -74.6894989013672
    ],
    center: [-77.7278831, 40.9699889]
  },
  'Rhode Island': {
    state: 'Rhode Island',
    percentInDesertsAll: 0.24,
    percentInDesertsBlack: 0.39,
    percentInDesertsWhite: 0.98,
    percentInDesertsHispanic: 0.3,
    chidrenUnder5InDesertsRural: 63178,
    childrenUnder5NotInDesertsRural: 49801,
    childrenUnder5InDesertsSuburban: 718507,
    childrenUnder5NotInDesertsSuburban: 556368,
    childrenUnder5InDesertsUrban: 59354,
    childrenUnder5NotInDesertsUrban: 80711,
    textBox: 'Text about Rhode Island',
    abbr: 'RI',
    bounds: [
      41.055534362793,
      42.018856048584,
      -71.9070053100586,
      -71.1204681396484
    ],
    center: [-71.5992372, 41.7962409]
  },
  'South Carolina': {
    state: 'South Carolina',
    percentInDesertsAll: 0.79,
    percentInDesertsBlack: 0.62,
    percentInDesertsWhite: 0.49,
    percentInDesertsHispanic: 0.51,
    chidrenUnder5InDesertsRural: 79265,
    childrenUnder5NotInDesertsRural: 33659,
    childrenUnder5InDesertsSuburban: 317327,
    childrenUnder5NotInDesertsSuburban: 296063,
    childrenUnder5InDesertsUrban: 51959,
    childrenUnder5NotInDesertsUrban: 123661,
    textBox: 'Text about South Carolina',
    abbr: 'SC',
    bounds: [
      32.0333099365234,
      35.2155418395996,
      -83.35400390625,
      -78.4992980957031
    ],
    center: [-80.4363743, 33.6874388]
  },
  'South Dakota': {
    state: 'South Dakota',
    percentInDesertsAll: 0.14,
    percentInDesertsBlack: 0.42,
    percentInDesertsWhite: 0.48,
    percentInDesertsHispanic: 0.73,
    chidrenUnder5InDesertsRural: 66797,
    childrenUnder5NotInDesertsRural: 52414,
    childrenUnder5InDesertsSuburban: 464927,
    childrenUnder5NotInDesertsSuburban: 373853,
    childrenUnder5InDesertsUrban: 43646,
    childrenUnder5NotInDesertsUrban: 65226,
    textBox: 'Text about South Dakota',
    abbr: 'SD',
    bounds: [
      42.4798889160156,
      45.9454536437988,
      -104.05770111084,
      -96.4363327026367
    ],
    center: [-100.348761, 44.6471761]
  },
  Texas: {
    state: 'Texas',
    percentInDesertsAll: 0.42,
    percentInDesertsBlack: 0.59,
    percentInDesertsWhite: 0.14,
    percentInDesertsHispanic: 0.83,
    chidrenUnder5InDesertsRural: 40417,
    childrenUnder5NotInDesertsRural: 45788,
    childrenUnder5InDesertsSuburban: 458977,
    childrenUnder5NotInDesertsSuburban: 354912,
    childrenUnder5InDesertsUrban: 52077,
    childrenUnder5NotInDesertsUrban: 131410,
    textBox: 'Text about Texas',
    abbr: 'TX',
    bounds: [
      25.8370609283447,
      36.5007057189941,
      -106.645652770996,
      -93.5078201293945
    ],
    center: [-99.5120986, 31.8160381]
  },
  Vermont: {
    state: 'Vermont',
    percentInDesertsAll: 0.9,
    percentInDesertsBlack: 0.49,
    percentInDesertsWhite: 0.82,
    percentInDesertsHispanic: 0.14,
    chidrenUnder5InDesertsRural: 54105,
    childrenUnder5NotInDesertsRural: 49610,
    childrenUnder5InDesertsSuburban: 229892,
    childrenUnder5NotInDesertsSuburban: 326465,
    childrenUnder5InDesertsUrban: 53088,
    childrenUnder5NotInDesertsUrban: 107070,
    textBox: 'Text about Vermont',
    abbr: 'VT',
    bounds: [
      42.7269325256348,
      45.0166664123535,
      -73.437744140625,
      -71.4653549194336
    ],
    center: [-72.5002608, 44.5990718]
  }
};
